(defun is-nil (x)
  (null x))
(compile 'is-nil)
(disassemble 'is-nil)

(defun test ()
  (let ((a 1)
        (b (+ 1 2)))
    (+ a b)))
(compile 'test)
(disassemble 'test)
(disassemble (compile nil '(lambda ()
                            (let ((a 1)
                                  (b (+ 1 2)))
                              (+ a b)))))
